spring.application.name=autoshop
server.servlet.context-path=/autoshop

# DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/autoshop
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate/JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true